/*
 * generated by Xtext 2.24.0
 */
package com.karalisoft.ui.tests;

import com.google.inject.Injector;
import com.karalisoft.scad.ui.internal.ScadActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ScadUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ScadActivator.getInstance().getInjector("com.karalisoft.Scad");
	}

}
