/*
 * generated by Xtext 2.24.0
 */
package com.karalisoft.ui;

import com.google.inject.Injector;
import com.karalisoft.scad.ui.internal.ScadActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ScadExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(ScadActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		ScadActivator activator = ScadActivator.getInstance();
		return activator != null ? activator.getInjector(ScadActivator.COM_KARALISOFT_SCAD) : null;
	}

}
