/**
 * generated by Xtext 2.24.0
 */
package com.karalisoft.scad.impl;

import com.karalisoft.scad.CylinderParams;
import com.karalisoft.scad.ScadPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Cylinder Params</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.karalisoft.scad.impl.CylinderParamsImpl#getFn <em>Fn</em>}</li>
 *   <li>{@link com.karalisoft.scad.impl.CylinderParamsImpl#getFa <em>Fa</em>}</li>
 *   <li>{@link com.karalisoft.scad.impl.CylinderParamsImpl#getFs <em>Fs</em>}</li>
 *   <li>{@link com.karalisoft.scad.impl.CylinderParamsImpl#getH <em>H</em>}</li>
 *   <li>{@link com.karalisoft.scad.impl.CylinderParamsImpl#getR <em>R</em>}</li>
 *   <li>{@link com.karalisoft.scad.impl.CylinderParamsImpl#getR1 <em>R1</em>}</li>
 *   <li>{@link com.karalisoft.scad.impl.CylinderParamsImpl#getR2 <em>R2</em>}</li>
 *   <li>{@link com.karalisoft.scad.impl.CylinderParamsImpl#getD <em>D</em>}</li>
 *   <li>{@link com.karalisoft.scad.impl.CylinderParamsImpl#getD1 <em>D1</em>}</li>
 *   <li>{@link com.karalisoft.scad.impl.CylinderParamsImpl#getD2 <em>D2</em>}</li>
 *   <li>{@link com.karalisoft.scad.impl.CylinderParamsImpl#getCenter <em>Center</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CylinderParamsImpl extends MinimalEObjectImpl.Container implements CylinderParams
{
  /**
   * The default value of the '{@link #getFn() <em>Fn</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFn()
   * @generated
   * @ordered
   */
  protected static final Double FN_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFn() <em>Fn</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFn()
   * @generated
   * @ordered
   */
  protected Double fn = FN_EDEFAULT;

  /**
   * The default value of the '{@link #getFa() <em>Fa</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFa()
   * @generated
   * @ordered
   */
  protected static final Double FA_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFa() <em>Fa</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFa()
   * @generated
   * @ordered
   */
  protected Double fa = FA_EDEFAULT;

  /**
   * The default value of the '{@link #getFs() <em>Fs</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFs()
   * @generated
   * @ordered
   */
  protected static final Double FS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFs() <em>Fs</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFs()
   * @generated
   * @ordered
   */
  protected Double fs = FS_EDEFAULT;

  /**
   * The default value of the '{@link #getH() <em>H</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getH()
   * @generated
   * @ordered
   */
  protected static final Double H_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getH() <em>H</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getH()
   * @generated
   * @ordered
   */
  protected Double h = H_EDEFAULT;

  /**
   * The default value of the '{@link #getR() <em>R</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getR()
   * @generated
   * @ordered
   */
  protected static final Double R_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getR() <em>R</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getR()
   * @generated
   * @ordered
   */
  protected Double r = R_EDEFAULT;

  /**
   * The default value of the '{@link #getR1() <em>R1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getR1()
   * @generated
   * @ordered
   */
  protected static final Double R1_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getR1() <em>R1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getR1()
   * @generated
   * @ordered
   */
  protected Double r1 = R1_EDEFAULT;

  /**
   * The default value of the '{@link #getR2() <em>R2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getR2()
   * @generated
   * @ordered
   */
  protected static final Double R2_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getR2() <em>R2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getR2()
   * @generated
   * @ordered
   */
  protected Double r2 = R2_EDEFAULT;

  /**
   * The default value of the '{@link #getD() <em>D</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getD()
   * @generated
   * @ordered
   */
  protected static final Double D_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getD() <em>D</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getD()
   * @generated
   * @ordered
   */
  protected Double d = D_EDEFAULT;

  /**
   * The default value of the '{@link #getD1() <em>D1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getD1()
   * @generated
   * @ordered
   */
  protected static final Double D1_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getD1() <em>D1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getD1()
   * @generated
   * @ordered
   */
  protected Double d1 = D1_EDEFAULT;

  /**
   * The default value of the '{@link #getD2() <em>D2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getD2()
   * @generated
   * @ordered
   */
  protected static final Double D2_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getD2() <em>D2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getD2()
   * @generated
   * @ordered
   */
  protected Double d2 = D2_EDEFAULT;

  /**
   * The default value of the '{@link #getCenter() <em>Center</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCenter()
   * @generated
   * @ordered
   */
  protected static final String CENTER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCenter() <em>Center</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCenter()
   * @generated
   * @ordered
   */
  protected String center = CENTER_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CylinderParamsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ScadPackage.Literals.CYLINDER_PARAMS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Double getFn()
  {
    return fn;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFn(Double newFn)
  {
    Double oldFn = fn;
    fn = newFn;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ScadPackage.CYLINDER_PARAMS__FN, oldFn, fn));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Double getFa()
  {
    return fa;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFa(Double newFa)
  {
    Double oldFa = fa;
    fa = newFa;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ScadPackage.CYLINDER_PARAMS__FA, oldFa, fa));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Double getFs()
  {
    return fs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFs(Double newFs)
  {
    Double oldFs = fs;
    fs = newFs;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ScadPackage.CYLINDER_PARAMS__FS, oldFs, fs));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Double getH()
  {
    return h;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setH(Double newH)
  {
    Double oldH = h;
    h = newH;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ScadPackage.CYLINDER_PARAMS__H, oldH, h));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Double getR()
  {
    return r;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setR(Double newR)
  {
    Double oldR = r;
    r = newR;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ScadPackage.CYLINDER_PARAMS__R, oldR, r));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Double getR1()
  {
    return r1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setR1(Double newR1)
  {
    Double oldR1 = r1;
    r1 = newR1;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ScadPackage.CYLINDER_PARAMS__R1, oldR1, r1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Double getR2()
  {
    return r2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setR2(Double newR2)
  {
    Double oldR2 = r2;
    r2 = newR2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ScadPackage.CYLINDER_PARAMS__R2, oldR2, r2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Double getD()
  {
    return d;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setD(Double newD)
  {
    Double oldD = d;
    d = newD;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ScadPackage.CYLINDER_PARAMS__D, oldD, d));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Double getD1()
  {
    return d1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setD1(Double newD1)
  {
    Double oldD1 = d1;
    d1 = newD1;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ScadPackage.CYLINDER_PARAMS__D1, oldD1, d1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Double getD2()
  {
    return d2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setD2(Double newD2)
  {
    Double oldD2 = d2;
    d2 = newD2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ScadPackage.CYLINDER_PARAMS__D2, oldD2, d2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCenter()
  {
    return center;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCenter(String newCenter)
  {
    String oldCenter = center;
    center = newCenter;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ScadPackage.CYLINDER_PARAMS__CENTER, oldCenter, center));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ScadPackage.CYLINDER_PARAMS__FN:
        return getFn();
      case ScadPackage.CYLINDER_PARAMS__FA:
        return getFa();
      case ScadPackage.CYLINDER_PARAMS__FS:
        return getFs();
      case ScadPackage.CYLINDER_PARAMS__H:
        return getH();
      case ScadPackage.CYLINDER_PARAMS__R:
        return getR();
      case ScadPackage.CYLINDER_PARAMS__R1:
        return getR1();
      case ScadPackage.CYLINDER_PARAMS__R2:
        return getR2();
      case ScadPackage.CYLINDER_PARAMS__D:
        return getD();
      case ScadPackage.CYLINDER_PARAMS__D1:
        return getD1();
      case ScadPackage.CYLINDER_PARAMS__D2:
        return getD2();
      case ScadPackage.CYLINDER_PARAMS__CENTER:
        return getCenter();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ScadPackage.CYLINDER_PARAMS__FN:
        setFn((Double)newValue);
        return;
      case ScadPackage.CYLINDER_PARAMS__FA:
        setFa((Double)newValue);
        return;
      case ScadPackage.CYLINDER_PARAMS__FS:
        setFs((Double)newValue);
        return;
      case ScadPackage.CYLINDER_PARAMS__H:
        setH((Double)newValue);
        return;
      case ScadPackage.CYLINDER_PARAMS__R:
        setR((Double)newValue);
        return;
      case ScadPackage.CYLINDER_PARAMS__R1:
        setR1((Double)newValue);
        return;
      case ScadPackage.CYLINDER_PARAMS__R2:
        setR2((Double)newValue);
        return;
      case ScadPackage.CYLINDER_PARAMS__D:
        setD((Double)newValue);
        return;
      case ScadPackage.CYLINDER_PARAMS__D1:
        setD1((Double)newValue);
        return;
      case ScadPackage.CYLINDER_PARAMS__D2:
        setD2((Double)newValue);
        return;
      case ScadPackage.CYLINDER_PARAMS__CENTER:
        setCenter((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ScadPackage.CYLINDER_PARAMS__FN:
        setFn(FN_EDEFAULT);
        return;
      case ScadPackage.CYLINDER_PARAMS__FA:
        setFa(FA_EDEFAULT);
        return;
      case ScadPackage.CYLINDER_PARAMS__FS:
        setFs(FS_EDEFAULT);
        return;
      case ScadPackage.CYLINDER_PARAMS__H:
        setH(H_EDEFAULT);
        return;
      case ScadPackage.CYLINDER_PARAMS__R:
        setR(R_EDEFAULT);
        return;
      case ScadPackage.CYLINDER_PARAMS__R1:
        setR1(R1_EDEFAULT);
        return;
      case ScadPackage.CYLINDER_PARAMS__R2:
        setR2(R2_EDEFAULT);
        return;
      case ScadPackage.CYLINDER_PARAMS__D:
        setD(D_EDEFAULT);
        return;
      case ScadPackage.CYLINDER_PARAMS__D1:
        setD1(D1_EDEFAULT);
        return;
      case ScadPackage.CYLINDER_PARAMS__D2:
        setD2(D2_EDEFAULT);
        return;
      case ScadPackage.CYLINDER_PARAMS__CENTER:
        setCenter(CENTER_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ScadPackage.CYLINDER_PARAMS__FN:
        return FN_EDEFAULT == null ? fn != null : !FN_EDEFAULT.equals(fn);
      case ScadPackage.CYLINDER_PARAMS__FA:
        return FA_EDEFAULT == null ? fa != null : !FA_EDEFAULT.equals(fa);
      case ScadPackage.CYLINDER_PARAMS__FS:
        return FS_EDEFAULT == null ? fs != null : !FS_EDEFAULT.equals(fs);
      case ScadPackage.CYLINDER_PARAMS__H:
        return H_EDEFAULT == null ? h != null : !H_EDEFAULT.equals(h);
      case ScadPackage.CYLINDER_PARAMS__R:
        return R_EDEFAULT == null ? r != null : !R_EDEFAULT.equals(r);
      case ScadPackage.CYLINDER_PARAMS__R1:
        return R1_EDEFAULT == null ? r1 != null : !R1_EDEFAULT.equals(r1);
      case ScadPackage.CYLINDER_PARAMS__R2:
        return R2_EDEFAULT == null ? r2 != null : !R2_EDEFAULT.equals(r2);
      case ScadPackage.CYLINDER_PARAMS__D:
        return D_EDEFAULT == null ? d != null : !D_EDEFAULT.equals(d);
      case ScadPackage.CYLINDER_PARAMS__D1:
        return D1_EDEFAULT == null ? d1 != null : !D1_EDEFAULT.equals(d1);
      case ScadPackage.CYLINDER_PARAMS__D2:
        return D2_EDEFAULT == null ? d2 != null : !D2_EDEFAULT.equals(d2);
      case ScadPackage.CYLINDER_PARAMS__CENTER:
        return CENTER_EDEFAULT == null ? center != null : !CENTER_EDEFAULT.equals(center);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (fn: ");
    result.append(fn);
    result.append(", fa: ");
    result.append(fa);
    result.append(", fs: ");
    result.append(fs);
    result.append(", h: ");
    result.append(h);
    result.append(", r: ");
    result.append(r);
    result.append(", r1: ");
    result.append(r1);
    result.append(", r2: ");
    result.append(r2);
    result.append(", d: ");
    result.append(d);
    result.append(", d1: ");
    result.append(d1);
    result.append(", d2: ");
    result.append(d2);
    result.append(", center: ");
    result.append(center);
    result.append(')');
    return result.toString();
  }

} //CylinderParamsImpl
