/**
 * generated by Xtext 2.24.0
 */
package com.karalisoft.scad.impl;

import com.karalisoft.scad.ScadPackage;
import com.karalisoft.scad.Shape;
import com.karalisoft.scad.Transformation;
import com.karalisoft.scad.TransformedShape;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Transformed Shape</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.karalisoft.scad.impl.TransformedShapeImpl#getTranslations <em>Translations</em>}</li>
 *   <li>{@link com.karalisoft.scad.impl.TransformedShapeImpl#getImpl <em>Impl</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TransformedShapeImpl extends MinimalEObjectImpl.Container implements TransformedShape
{
  /**
   * The cached value of the '{@link #getTranslations() <em>Translations</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTranslations()
   * @generated
   * @ordered
   */
  protected EList<Transformation> translations;

  /**
   * The cached value of the '{@link #getImpl() <em>Impl</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImpl()
   * @generated
   * @ordered
   */
  protected EList<Shape> impl;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TransformedShapeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ScadPackage.Literals.TRANSFORMED_SHAPE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Transformation> getTranslations()
  {
    if (translations == null)
    {
      translations = new EObjectContainmentEList<Transformation>(Transformation.class, this, ScadPackage.TRANSFORMED_SHAPE__TRANSLATIONS);
    }
    return translations;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Shape> getImpl()
  {
    if (impl == null)
    {
      impl = new EObjectContainmentEList<Shape>(Shape.class, this, ScadPackage.TRANSFORMED_SHAPE__IMPL);
    }
    return impl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ScadPackage.TRANSFORMED_SHAPE__TRANSLATIONS:
        return ((InternalEList<?>)getTranslations()).basicRemove(otherEnd, msgs);
      case ScadPackage.TRANSFORMED_SHAPE__IMPL:
        return ((InternalEList<?>)getImpl()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ScadPackage.TRANSFORMED_SHAPE__TRANSLATIONS:
        return getTranslations();
      case ScadPackage.TRANSFORMED_SHAPE__IMPL:
        return getImpl();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ScadPackage.TRANSFORMED_SHAPE__TRANSLATIONS:
        getTranslations().clear();
        getTranslations().addAll((Collection<? extends Transformation>)newValue);
        return;
      case ScadPackage.TRANSFORMED_SHAPE__IMPL:
        getImpl().clear();
        getImpl().addAll((Collection<? extends Shape>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ScadPackage.TRANSFORMED_SHAPE__TRANSLATIONS:
        getTranslations().clear();
        return;
      case ScadPackage.TRANSFORMED_SHAPE__IMPL:
        getImpl().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ScadPackage.TRANSFORMED_SHAPE__TRANSLATIONS:
        return translations != null && !translations.isEmpty();
      case ScadPackage.TRANSFORMED_SHAPE__IMPL:
        return impl != null && !impl.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //TransformedShapeImpl
