/**
 * generated by Xtext 2.24.0
 */
package com.karalisoft.scad.impl;

import com.karalisoft.scad.ScadPackage;
import com.karalisoft.scad.UseOrInclude;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Use Or Include</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class UseOrIncludeImpl extends MinimalEObjectImpl.Container implements UseOrInclude
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UseOrIncludeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ScadPackage.Literals.USE_OR_INCLUDE;
  }

} //UseOrIncludeImpl
