/**
 * generated by Xtext 2.24.0
 */
package com.karalisoft.scad;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cube Params</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.karalisoft.scad.CubeParams#getSize <em>Size</em>}</li>
 *   <li>{@link com.karalisoft.scad.CubeParams#getX <em>X</em>}</li>
 *   <li>{@link com.karalisoft.scad.CubeParams#getY <em>Y</em>}</li>
 *   <li>{@link com.karalisoft.scad.CubeParams#getZ <em>Z</em>}</li>
 *   <li>{@link com.karalisoft.scad.CubeParams#getCenter <em>Center</em>}</li>
 * </ul>
 *
 * @see com.karalisoft.scad.ScadPackage#getCubeParams()
 * @model
 * @generated
 */
public interface CubeParams extends EObject
{
  /**
   * Returns the value of the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Size</em>' attribute.
   * @see #setSize(Double)
   * @see com.karalisoft.scad.ScadPackage#getCubeParams_Size()
   * @model
   * @generated
   */
  Double getSize();

  /**
   * Sets the value of the '{@link com.karalisoft.scad.CubeParams#getSize <em>Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Size</em>' attribute.
   * @see #getSize()
   * @generated
   */
  void setSize(Double value);

  /**
   * Returns the value of the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>X</em>' attribute.
   * @see #setX(Double)
   * @see com.karalisoft.scad.ScadPackage#getCubeParams_X()
   * @model
   * @generated
   */
  Double getX();

  /**
   * Sets the value of the '{@link com.karalisoft.scad.CubeParams#getX <em>X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X</em>' attribute.
   * @see #getX()
   * @generated
   */
  void setX(Double value);

  /**
   * Returns the value of the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Y</em>' attribute.
   * @see #setY(Double)
   * @see com.karalisoft.scad.ScadPackage#getCubeParams_Y()
   * @model
   * @generated
   */
  Double getY();

  /**
   * Sets the value of the '{@link com.karalisoft.scad.CubeParams#getY <em>Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Y</em>' attribute.
   * @see #getY()
   * @generated
   */
  void setY(Double value);

  /**
   * Returns the value of the '<em><b>Z</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Z</em>' attribute.
   * @see #setZ(Double)
   * @see com.karalisoft.scad.ScadPackage#getCubeParams_Z()
   * @model
   * @generated
   */
  Double getZ();

  /**
   * Sets the value of the '{@link com.karalisoft.scad.CubeParams#getZ <em>Z</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Z</em>' attribute.
   * @see #getZ()
   * @generated
   */
  void setZ(Double value);

  /**
   * Returns the value of the '<em><b>Center</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Center</em>' attribute.
   * @see #setCenter(String)
   * @see com.karalisoft.scad.ScadPackage#getCubeParams_Center()
   * @model
   * @generated
   */
  String getCenter();

  /**
   * Sets the value of the '{@link com.karalisoft.scad.CubeParams#getCenter <em>Center</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Center</em>' attribute.
   * @see #getCenter()
   * @generated
   */
  void setCenter(String value);

} // CubeParams
