/**
 * generated by Xtext 2.24.0
 */
package com.karalisoft.scad;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cylinder</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.karalisoft.scad.Cylinder#getCylinderParams <em>Cylinder Params</em>}</li>
 * </ul>
 *
 * @see com.karalisoft.scad.ScadPackage#getCylinder()
 * @model
 * @generated
 */
public interface Cylinder extends EObject
{
  /**
   * Returns the value of the '<em><b>Cylinder Params</b></em>' containment reference list.
   * The list contents are of type {@link com.karalisoft.scad.CylinderParams}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cylinder Params</em>' containment reference list.
   * @see com.karalisoft.scad.ScadPackage#getCylinder_CylinderParams()
   * @model containment="true"
   * @generated
   */
  EList<CylinderParams> getCylinderParams();

} // Cylinder
