/**
 * generated by Xtext 2.24.0
 */
package com.karalisoft.scad;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cylinder Params</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.karalisoft.scad.CylinderParams#getFn <em>Fn</em>}</li>
 *   <li>{@link com.karalisoft.scad.CylinderParams#getFa <em>Fa</em>}</li>
 *   <li>{@link com.karalisoft.scad.CylinderParams#getFs <em>Fs</em>}</li>
 *   <li>{@link com.karalisoft.scad.CylinderParams#getH <em>H</em>}</li>
 *   <li>{@link com.karalisoft.scad.CylinderParams#getR <em>R</em>}</li>
 *   <li>{@link com.karalisoft.scad.CylinderParams#getR1 <em>R1</em>}</li>
 *   <li>{@link com.karalisoft.scad.CylinderParams#getR2 <em>R2</em>}</li>
 *   <li>{@link com.karalisoft.scad.CylinderParams#getD <em>D</em>}</li>
 *   <li>{@link com.karalisoft.scad.CylinderParams#getD1 <em>D1</em>}</li>
 *   <li>{@link com.karalisoft.scad.CylinderParams#getD2 <em>D2</em>}</li>
 *   <li>{@link com.karalisoft.scad.CylinderParams#getCenter <em>Center</em>}</li>
 * </ul>
 *
 * @see com.karalisoft.scad.ScadPackage#getCylinderParams()
 * @model
 * @generated
 */
public interface CylinderParams extends EObject
{
  /**
   * Returns the value of the '<em><b>Fn</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fn</em>' attribute.
   * @see #setFn(Double)
   * @see com.karalisoft.scad.ScadPackage#getCylinderParams_Fn()
   * @model
   * @generated
   */
  Double getFn();

  /**
   * Sets the value of the '{@link com.karalisoft.scad.CylinderParams#getFn <em>Fn</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fn</em>' attribute.
   * @see #getFn()
   * @generated
   */
  void setFn(Double value);

  /**
   * Returns the value of the '<em><b>Fa</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fa</em>' attribute.
   * @see #setFa(Double)
   * @see com.karalisoft.scad.ScadPackage#getCylinderParams_Fa()
   * @model
   * @generated
   */
  Double getFa();

  /**
   * Sets the value of the '{@link com.karalisoft.scad.CylinderParams#getFa <em>Fa</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fa</em>' attribute.
   * @see #getFa()
   * @generated
   */
  void setFa(Double value);

  /**
   * Returns the value of the '<em><b>Fs</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fs</em>' attribute.
   * @see #setFs(Double)
   * @see com.karalisoft.scad.ScadPackage#getCylinderParams_Fs()
   * @model
   * @generated
   */
  Double getFs();

  /**
   * Sets the value of the '{@link com.karalisoft.scad.CylinderParams#getFs <em>Fs</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fs</em>' attribute.
   * @see #getFs()
   * @generated
   */
  void setFs(Double value);

  /**
   * Returns the value of the '<em><b>H</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>H</em>' attribute.
   * @see #setH(Double)
   * @see com.karalisoft.scad.ScadPackage#getCylinderParams_H()
   * @model
   * @generated
   */
  Double getH();

  /**
   * Sets the value of the '{@link com.karalisoft.scad.CylinderParams#getH <em>H</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>H</em>' attribute.
   * @see #getH()
   * @generated
   */
  void setH(Double value);

  /**
   * Returns the value of the '<em><b>R</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>R</em>' attribute.
   * @see #setR(Double)
   * @see com.karalisoft.scad.ScadPackage#getCylinderParams_R()
   * @model
   * @generated
   */
  Double getR();

  /**
   * Sets the value of the '{@link com.karalisoft.scad.CylinderParams#getR <em>R</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>R</em>' attribute.
   * @see #getR()
   * @generated
   */
  void setR(Double value);

  /**
   * Returns the value of the '<em><b>R1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>R1</em>' attribute.
   * @see #setR1(Double)
   * @see com.karalisoft.scad.ScadPackage#getCylinderParams_R1()
   * @model
   * @generated
   */
  Double getR1();

  /**
   * Sets the value of the '{@link com.karalisoft.scad.CylinderParams#getR1 <em>R1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>R1</em>' attribute.
   * @see #getR1()
   * @generated
   */
  void setR1(Double value);

  /**
   * Returns the value of the '<em><b>R2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>R2</em>' attribute.
   * @see #setR2(Double)
   * @see com.karalisoft.scad.ScadPackage#getCylinderParams_R2()
   * @model
   * @generated
   */
  Double getR2();

  /**
   * Sets the value of the '{@link com.karalisoft.scad.CylinderParams#getR2 <em>R2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>R2</em>' attribute.
   * @see #getR2()
   * @generated
   */
  void setR2(Double value);

  /**
   * Returns the value of the '<em><b>D</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>D</em>' attribute.
   * @see #setD(Double)
   * @see com.karalisoft.scad.ScadPackage#getCylinderParams_D()
   * @model
   * @generated
   */
  Double getD();

  /**
   * Sets the value of the '{@link com.karalisoft.scad.CylinderParams#getD <em>D</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>D</em>' attribute.
   * @see #getD()
   * @generated
   */
  void setD(Double value);

  /**
   * Returns the value of the '<em><b>D1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>D1</em>' attribute.
   * @see #setD1(Double)
   * @see com.karalisoft.scad.ScadPackage#getCylinderParams_D1()
   * @model
   * @generated
   */
  Double getD1();

  /**
   * Sets the value of the '{@link com.karalisoft.scad.CylinderParams#getD1 <em>D1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>D1</em>' attribute.
   * @see #getD1()
   * @generated
   */
  void setD1(Double value);

  /**
   * Returns the value of the '<em><b>D2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>D2</em>' attribute.
   * @see #setD2(Double)
   * @see com.karalisoft.scad.ScadPackage#getCylinderParams_D2()
   * @model
   * @generated
   */
  Double getD2();

  /**
   * Sets the value of the '{@link com.karalisoft.scad.CylinderParams#getD2 <em>D2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>D2</em>' attribute.
   * @see #getD2()
   * @generated
   */
  void setD2(Double value);

  /**
   * Returns the value of the '<em><b>Center</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Center</em>' attribute.
   * @see #setCenter(String)
   * @see com.karalisoft.scad.ScadPackage#getCylinderParams_Center()
   * @model
   * @generated
   */
  String getCenter();

  /**
   * Sets the value of the '{@link com.karalisoft.scad.CylinderParams#getCenter <em>Center</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Center</em>' attribute.
   * @see #getCenter()
   * @generated
   */
  void setCenter(String value);

} // CylinderParams
