/**
 * generated by Xtext 2.24.0
 */
package com.karalisoft.scad;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.karalisoft.scad.ScadPackage#getFunction()
 * @model
 * @generated
 */
public interface Function extends ModuleOrFunction
{
} // Function
