/**
 * generated by Xtext 2.24.0
 */
package com.karalisoft.scad;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Module</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.karalisoft.scad.Module#getBlocks <em>Blocks</em>}</li>
 * </ul>
 *
 * @see com.karalisoft.scad.ScadPackage#getModule()
 * @model
 * @generated
 */
public interface Module extends ModuleOrFunction
{
  /**
   * Returns the value of the '<em><b>Blocks</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Blocks</em>' containment reference list.
   * @see com.karalisoft.scad.ScadPackage#getModule_Blocks()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getBlocks();

} // Module
