/**
 * generated by Xtext 2.24.0
 */
package com.karalisoft.scad;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rotate</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.karalisoft.scad.ScadPackage#getRotate()
 * @model
 * @generated
 */
public interface Rotate extends Transformation
{
} // Rotate
