/**
 * generated by Xtext 2.24.0
 */
package com.karalisoft.scad;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.karalisoft.scad.ScadFactory
 * @model kind="package"
 * @generated
 */
public interface ScadPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "scad";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.karalisoft.com/Scad";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "scad";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ScadPackage eINSTANCE = com.karalisoft.scad.impl.ScadPackageImpl.init();

  /**
   * The meta object id for the '{@link com.karalisoft.scad.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.karalisoft.scad.impl.ModelImpl
   * @see com.karalisoft.scad.impl.ScadPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Blocks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__BLOCKS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.karalisoft.scad.impl.ModuleOrFunctionImpl <em>Module Or Function</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.karalisoft.scad.impl.ModuleOrFunctionImpl
   * @see com.karalisoft.scad.impl.ScadPackageImpl#getModuleOrFunction()
   * @generated
   */
  int MODULE_OR_FUNCTION = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODULE_OR_FUNCTION__NAME = 0;

  /**
   * The number of structural features of the '<em>Module Or Function</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODULE_OR_FUNCTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.karalisoft.scad.impl.UseOrIncludeImpl <em>Use Or Include</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.karalisoft.scad.impl.UseOrIncludeImpl
   * @see com.karalisoft.scad.impl.ScadPackageImpl#getUseOrInclude()
   * @generated
   */
  int USE_OR_INCLUDE = 2;

  /**
   * The number of structural features of the '<em>Use Or Include</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USE_OR_INCLUDE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.karalisoft.scad.impl.ModuleImpl <em>Module</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.karalisoft.scad.impl.ModuleImpl
   * @see com.karalisoft.scad.impl.ScadPackageImpl#getModule()
   * @generated
   */
  int MODULE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODULE__NAME = MODULE_OR_FUNCTION__NAME;

  /**
   * The feature id for the '<em><b>Blocks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODULE__BLOCKS = MODULE_OR_FUNCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Module</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODULE_FEATURE_COUNT = MODULE_OR_FUNCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.karalisoft.scad.impl.FunctionImpl <em>Function</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.karalisoft.scad.impl.FunctionImpl
   * @see com.karalisoft.scad.impl.ScadPackageImpl#getFunction()
   * @generated
   */
  int FUNCTION = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__NAME = MODULE_OR_FUNCTION__NAME;

  /**
   * The number of structural features of the '<em>Function</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_FEATURE_COUNT = MODULE_OR_FUNCTION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.karalisoft.scad.impl.ModuleOrFunctionCallImpl <em>Module Or Function Call</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.karalisoft.scad.impl.ModuleOrFunctionCallImpl
   * @see com.karalisoft.scad.impl.ScadPackageImpl#getModuleOrFunctionCall()
   * @generated
   */
  int MODULE_OR_FUNCTION_CALL = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODULE_OR_FUNCTION_CALL__NAME = 0;

  /**
   * The number of structural features of the '<em>Module Or Function Call</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODULE_OR_FUNCTION_CALL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.karalisoft.scad.impl.TransformationImpl <em>Transformation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.karalisoft.scad.impl.TransformationImpl
   * @see com.karalisoft.scad.impl.ScadPackageImpl#getTransformation()
   * @generated
   */
  int TRANSFORMATION = 6;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSFORMATION__X = 0;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSFORMATION__Y = 1;

  /**
   * The feature id for the '<em><b>Z</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSFORMATION__Z = 2;

  /**
   * The number of structural features of the '<em>Transformation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSFORMATION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link com.karalisoft.scad.impl.TranslateImpl <em>Translate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.karalisoft.scad.impl.TranslateImpl
   * @see com.karalisoft.scad.impl.ScadPackageImpl#getTranslate()
   * @generated
   */
  int TRANSLATE = 7;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSLATE__X = TRANSFORMATION__X;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSLATE__Y = TRANSFORMATION__Y;

  /**
   * The feature id for the '<em><b>Z</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSLATE__Z = TRANSFORMATION__Z;

  /**
   * The number of structural features of the '<em>Translate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSLATE_FEATURE_COUNT = TRANSFORMATION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.karalisoft.scad.impl.RotateImpl <em>Rotate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.karalisoft.scad.impl.RotateImpl
   * @see com.karalisoft.scad.impl.ScadPackageImpl#getRotate()
   * @generated
   */
  int ROTATE = 8;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE__X = TRANSFORMATION__X;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE__Y = TRANSFORMATION__Y;

  /**
   * The feature id for the '<em><b>Z</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE__Z = TRANSFORMATION__Z;

  /**
   * The number of structural features of the '<em>Rotate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_FEATURE_COUNT = TRANSFORMATION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link com.karalisoft.scad.impl.ScaleImpl <em>Scale</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.karalisoft.scad.impl.ScaleImpl
   * @see com.karalisoft.scad.impl.ScadPackageImpl#getScale()
   * @generated
   */
  int SCALE = 9;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCALE__X = TRANSFORMATION__X;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCALE__Y = TRANSFORMATION__Y;

  /**
   * The feature id for the '<em><b>Z</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCALE__Z = TRANSFORMATION__Z;

  /**
   * The feature id for the '<em><b>Scale</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCALE__SCALE = TRANSFORMATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Scale</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCALE_FEATURE_COUNT = TRANSFORMATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.karalisoft.scad.impl.ShapeImpl <em>Shape</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.karalisoft.scad.impl.ShapeImpl
   * @see com.karalisoft.scad.impl.ScadPackageImpl#getShape()
   * @generated
   */
  int SHAPE = 10;

  /**
   * The feature id for the '<em><b>Impl</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHAPE__IMPL = 0;

  /**
   * The number of structural features of the '<em>Shape</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SHAPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.karalisoft.scad.impl.TransformedShapeImpl <em>Transformed Shape</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.karalisoft.scad.impl.TransformedShapeImpl
   * @see com.karalisoft.scad.impl.ScadPackageImpl#getTransformedShape()
   * @generated
   */
  int TRANSFORMED_SHAPE = 11;

  /**
   * The feature id for the '<em><b>Translations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSFORMED_SHAPE__TRANSLATIONS = 0;

  /**
   * The feature id for the '<em><b>Impl</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSFORMED_SHAPE__IMPL = 1;

  /**
   * The number of structural features of the '<em>Transformed Shape</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSFORMED_SHAPE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.karalisoft.scad.impl.TransformedModuleOrFunctionCallImpl <em>Transformed Module Or Function Call</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.karalisoft.scad.impl.TransformedModuleOrFunctionCallImpl
   * @see com.karalisoft.scad.impl.ScadPackageImpl#getTransformedModuleOrFunctionCall()
   * @generated
   */
  int TRANSFORMED_MODULE_OR_FUNCTION_CALL = 12;

  /**
   * The feature id for the '<em><b>Translations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSFORMED_MODULE_OR_FUNCTION_CALL__TRANSLATIONS = 0;

  /**
   * The feature id for the '<em><b>Impl</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSFORMED_MODULE_OR_FUNCTION_CALL__IMPL = 1;

  /**
   * The number of structural features of the '<em>Transformed Module Or Function Call</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSFORMED_MODULE_OR_FUNCTION_CALL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.karalisoft.scad.impl.SphereImpl <em>Sphere</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.karalisoft.scad.impl.SphereImpl
   * @see com.karalisoft.scad.impl.ScadPackageImpl#getSphere()
   * @generated
   */
  int SPHERE = 13;

  /**
   * The feature id for the '<em><b>Sphere Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPHERE__SPHERE_PARAMS = 0;

  /**
   * The number of structural features of the '<em>Sphere</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPHERE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.karalisoft.scad.impl.SphereParamsImpl <em>Sphere Params</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.karalisoft.scad.impl.SphereParamsImpl
   * @see com.karalisoft.scad.impl.ScadPackageImpl#getSphereParams()
   * @generated
   */
  int SPHERE_PARAMS = 14;

  /**
   * The feature id for the '<em><b>Fn</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPHERE_PARAMS__FN = 0;

  /**
   * The feature id for the '<em><b>Fa</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPHERE_PARAMS__FA = 1;

  /**
   * The feature id for the '<em><b>Fs</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPHERE_PARAMS__FS = 2;

  /**
   * The feature id for the '<em><b>R</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPHERE_PARAMS__R = 3;

  /**
   * The feature id for the '<em><b>D</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPHERE_PARAMS__D = 4;

  /**
   * The number of structural features of the '<em>Sphere Params</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPHERE_PARAMS_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link com.karalisoft.scad.impl.CylinderImpl <em>Cylinder</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.karalisoft.scad.impl.CylinderImpl
   * @see com.karalisoft.scad.impl.ScadPackageImpl#getCylinder()
   * @generated
   */
  int CYLINDER = 15;

  /**
   * The feature id for the '<em><b>Cylinder Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CYLINDER__CYLINDER_PARAMS = 0;

  /**
   * The number of structural features of the '<em>Cylinder</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CYLINDER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.karalisoft.scad.impl.CylinderParamsImpl <em>Cylinder Params</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.karalisoft.scad.impl.CylinderParamsImpl
   * @see com.karalisoft.scad.impl.ScadPackageImpl#getCylinderParams()
   * @generated
   */
  int CYLINDER_PARAMS = 16;

  /**
   * The feature id for the '<em><b>Fn</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CYLINDER_PARAMS__FN = 0;

  /**
   * The feature id for the '<em><b>Fa</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CYLINDER_PARAMS__FA = 1;

  /**
   * The feature id for the '<em><b>Fs</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CYLINDER_PARAMS__FS = 2;

  /**
   * The feature id for the '<em><b>H</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CYLINDER_PARAMS__H = 3;

  /**
   * The feature id for the '<em><b>R</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CYLINDER_PARAMS__R = 4;

  /**
   * The feature id for the '<em><b>R1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CYLINDER_PARAMS__R1 = 5;

  /**
   * The feature id for the '<em><b>R2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CYLINDER_PARAMS__R2 = 6;

  /**
   * The feature id for the '<em><b>D</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CYLINDER_PARAMS__D = 7;

  /**
   * The feature id for the '<em><b>D1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CYLINDER_PARAMS__D1 = 8;

  /**
   * The feature id for the '<em><b>D2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CYLINDER_PARAMS__D2 = 9;

  /**
   * The feature id for the '<em><b>Center</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CYLINDER_PARAMS__CENTER = 10;

  /**
   * The number of structural features of the '<em>Cylinder Params</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CYLINDER_PARAMS_FEATURE_COUNT = 11;

  /**
   * The meta object id for the '{@link com.karalisoft.scad.impl.CubeImpl <em>Cube</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.karalisoft.scad.impl.CubeImpl
   * @see com.karalisoft.scad.impl.ScadPackageImpl#getCube()
   * @generated
   */
  int CUBE = 17;

  /**
   * The feature id for the '<em><b>Cube Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUBE__CUBE_PARAMS = 0;

  /**
   * The number of structural features of the '<em>Cube</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUBE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.karalisoft.scad.impl.CubeParamsImpl <em>Cube Params</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.karalisoft.scad.impl.CubeParamsImpl
   * @see com.karalisoft.scad.impl.ScadPackageImpl#getCubeParams()
   * @generated
   */
  int CUBE_PARAMS = 18;

  /**
   * The feature id for the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUBE_PARAMS__SIZE = 0;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUBE_PARAMS__X = 1;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUBE_PARAMS__Y = 2;

  /**
   * The feature id for the '<em><b>Z</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUBE_PARAMS__Z = 3;

  /**
   * The feature id for the '<em><b>Center</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUBE_PARAMS__CENTER = 4;

  /**
   * The number of structural features of the '<em>Cube Params</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUBE_PARAMS_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link com.karalisoft.scad.impl.UnionImpl <em>Union</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.karalisoft.scad.impl.UnionImpl
   * @see com.karalisoft.scad.impl.ScadPackageImpl#getUnion()
   * @generated
   */
  int UNION = 19;

  /**
   * The feature id for the '<em><b>Shapes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNION__SHAPES = 0;

  /**
   * The number of structural features of the '<em>Union</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.karalisoft.scad.impl.IntersectionImpl <em>Intersection</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.karalisoft.scad.impl.IntersectionImpl
   * @see com.karalisoft.scad.impl.ScadPackageImpl#getIntersection()
   * @generated
   */
  int INTERSECTION = 20;

  /**
   * The feature id for the '<em><b>Shapes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERSECTION__SHAPES = 0;

  /**
   * The number of structural features of the '<em>Intersection</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERSECTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.karalisoft.scad.impl.DifferenceImpl <em>Difference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.karalisoft.scad.impl.DifferenceImpl
   * @see com.karalisoft.scad.impl.ScadPackageImpl#getDifference()
   * @generated
   */
  int DIFFERENCE = 21;

  /**
   * The feature id for the '<em><b>Shapes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIFFERENCE__SHAPES = 0;

  /**
   * The number of structural features of the '<em>Difference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIFFERENCE_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link com.karalisoft.scad.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see com.karalisoft.scad.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link com.karalisoft.scad.Model#getBlocks <em>Blocks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Blocks</em>'.
   * @see com.karalisoft.scad.Model#getBlocks()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Blocks();

  /**
   * Returns the meta object for class '{@link com.karalisoft.scad.ModuleOrFunction <em>Module Or Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Module Or Function</em>'.
   * @see com.karalisoft.scad.ModuleOrFunction
   * @generated
   */
  EClass getModuleOrFunction();

  /**
   * Returns the meta object for the attribute '{@link com.karalisoft.scad.ModuleOrFunction#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.karalisoft.scad.ModuleOrFunction#getName()
   * @see #getModuleOrFunction()
   * @generated
   */
  EAttribute getModuleOrFunction_Name();

  /**
   * Returns the meta object for class '{@link com.karalisoft.scad.UseOrInclude <em>Use Or Include</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Use Or Include</em>'.
   * @see com.karalisoft.scad.UseOrInclude
   * @generated
   */
  EClass getUseOrInclude();

  /**
   * Returns the meta object for class '{@link com.karalisoft.scad.Module <em>Module</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Module</em>'.
   * @see com.karalisoft.scad.Module
   * @generated
   */
  EClass getModule();

  /**
   * Returns the meta object for the containment reference list '{@link com.karalisoft.scad.Module#getBlocks <em>Blocks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Blocks</em>'.
   * @see com.karalisoft.scad.Module#getBlocks()
   * @see #getModule()
   * @generated
   */
  EReference getModule_Blocks();

  /**
   * Returns the meta object for class '{@link com.karalisoft.scad.Function <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function</em>'.
   * @see com.karalisoft.scad.Function
   * @generated
   */
  EClass getFunction();

  /**
   * Returns the meta object for class '{@link com.karalisoft.scad.ModuleOrFunctionCall <em>Module Or Function Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Module Or Function Call</em>'.
   * @see com.karalisoft.scad.ModuleOrFunctionCall
   * @generated
   */
  EClass getModuleOrFunctionCall();

  /**
   * Returns the meta object for the attribute '{@link com.karalisoft.scad.ModuleOrFunctionCall#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.karalisoft.scad.ModuleOrFunctionCall#getName()
   * @see #getModuleOrFunctionCall()
   * @generated
   */
  EAttribute getModuleOrFunctionCall_Name();

  /**
   * Returns the meta object for class '{@link com.karalisoft.scad.Transformation <em>Transformation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transformation</em>'.
   * @see com.karalisoft.scad.Transformation
   * @generated
   */
  EClass getTransformation();

  /**
   * Returns the meta object for the attribute '{@link com.karalisoft.scad.Transformation#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see com.karalisoft.scad.Transformation#getX()
   * @see #getTransformation()
   * @generated
   */
  EAttribute getTransformation_X();

  /**
   * Returns the meta object for the attribute '{@link com.karalisoft.scad.Transformation#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see com.karalisoft.scad.Transformation#getY()
   * @see #getTransformation()
   * @generated
   */
  EAttribute getTransformation_Y();

  /**
   * Returns the meta object for the attribute '{@link com.karalisoft.scad.Transformation#getZ <em>Z</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Z</em>'.
   * @see com.karalisoft.scad.Transformation#getZ()
   * @see #getTransformation()
   * @generated
   */
  EAttribute getTransformation_Z();

  /**
   * Returns the meta object for class '{@link com.karalisoft.scad.Translate <em>Translate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Translate</em>'.
   * @see com.karalisoft.scad.Translate
   * @generated
   */
  EClass getTranslate();

  /**
   * Returns the meta object for class '{@link com.karalisoft.scad.Rotate <em>Rotate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rotate</em>'.
   * @see com.karalisoft.scad.Rotate
   * @generated
   */
  EClass getRotate();

  /**
   * Returns the meta object for class '{@link com.karalisoft.scad.Scale <em>Scale</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Scale</em>'.
   * @see com.karalisoft.scad.Scale
   * @generated
   */
  EClass getScale();

  /**
   * Returns the meta object for the attribute '{@link com.karalisoft.scad.Scale#getScale <em>Scale</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Scale</em>'.
   * @see com.karalisoft.scad.Scale#getScale()
   * @see #getScale()
   * @generated
   */
  EAttribute getScale_Scale();

  /**
   * Returns the meta object for class '{@link com.karalisoft.scad.Shape <em>Shape</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Shape</em>'.
   * @see com.karalisoft.scad.Shape
   * @generated
   */
  EClass getShape();

  /**
   * Returns the meta object for the containment reference '{@link com.karalisoft.scad.Shape#getImpl <em>Impl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Impl</em>'.
   * @see com.karalisoft.scad.Shape#getImpl()
   * @see #getShape()
   * @generated
   */
  EReference getShape_Impl();

  /**
   * Returns the meta object for class '{@link com.karalisoft.scad.TransformedShape <em>Transformed Shape</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transformed Shape</em>'.
   * @see com.karalisoft.scad.TransformedShape
   * @generated
   */
  EClass getTransformedShape();

  /**
   * Returns the meta object for the containment reference list '{@link com.karalisoft.scad.TransformedShape#getTranslations <em>Translations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Translations</em>'.
   * @see com.karalisoft.scad.TransformedShape#getTranslations()
   * @see #getTransformedShape()
   * @generated
   */
  EReference getTransformedShape_Translations();

  /**
   * Returns the meta object for the containment reference list '{@link com.karalisoft.scad.TransformedShape#getImpl <em>Impl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Impl</em>'.
   * @see com.karalisoft.scad.TransformedShape#getImpl()
   * @see #getTransformedShape()
   * @generated
   */
  EReference getTransformedShape_Impl();

  /**
   * Returns the meta object for class '{@link com.karalisoft.scad.TransformedModuleOrFunctionCall <em>Transformed Module Or Function Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transformed Module Or Function Call</em>'.
   * @see com.karalisoft.scad.TransformedModuleOrFunctionCall
   * @generated
   */
  EClass getTransformedModuleOrFunctionCall();

  /**
   * Returns the meta object for the containment reference list '{@link com.karalisoft.scad.TransformedModuleOrFunctionCall#getTranslations <em>Translations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Translations</em>'.
   * @see com.karalisoft.scad.TransformedModuleOrFunctionCall#getTranslations()
   * @see #getTransformedModuleOrFunctionCall()
   * @generated
   */
  EReference getTransformedModuleOrFunctionCall_Translations();

  /**
   * Returns the meta object for the containment reference list '{@link com.karalisoft.scad.TransformedModuleOrFunctionCall#getImpl <em>Impl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Impl</em>'.
   * @see com.karalisoft.scad.TransformedModuleOrFunctionCall#getImpl()
   * @see #getTransformedModuleOrFunctionCall()
   * @generated
   */
  EReference getTransformedModuleOrFunctionCall_Impl();

  /**
   * Returns the meta object for class '{@link com.karalisoft.scad.Sphere <em>Sphere</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sphere</em>'.
   * @see com.karalisoft.scad.Sphere
   * @generated
   */
  EClass getSphere();

  /**
   * Returns the meta object for the containment reference list '{@link com.karalisoft.scad.Sphere#getSphereParams <em>Sphere Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sphere Params</em>'.
   * @see com.karalisoft.scad.Sphere#getSphereParams()
   * @see #getSphere()
   * @generated
   */
  EReference getSphere_SphereParams();

  /**
   * Returns the meta object for class '{@link com.karalisoft.scad.SphereParams <em>Sphere Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sphere Params</em>'.
   * @see com.karalisoft.scad.SphereParams
   * @generated
   */
  EClass getSphereParams();

  /**
   * Returns the meta object for the attribute '{@link com.karalisoft.scad.SphereParams#getFn <em>Fn</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Fn</em>'.
   * @see com.karalisoft.scad.SphereParams#getFn()
   * @see #getSphereParams()
   * @generated
   */
  EAttribute getSphereParams_Fn();

  /**
   * Returns the meta object for the attribute '{@link com.karalisoft.scad.SphereParams#getFa <em>Fa</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Fa</em>'.
   * @see com.karalisoft.scad.SphereParams#getFa()
   * @see #getSphereParams()
   * @generated
   */
  EAttribute getSphereParams_Fa();

  /**
   * Returns the meta object for the attribute '{@link com.karalisoft.scad.SphereParams#getFs <em>Fs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Fs</em>'.
   * @see com.karalisoft.scad.SphereParams#getFs()
   * @see #getSphereParams()
   * @generated
   */
  EAttribute getSphereParams_Fs();

  /**
   * Returns the meta object for the attribute '{@link com.karalisoft.scad.SphereParams#getR <em>R</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>R</em>'.
   * @see com.karalisoft.scad.SphereParams#getR()
   * @see #getSphereParams()
   * @generated
   */
  EAttribute getSphereParams_R();

  /**
   * Returns the meta object for the attribute '{@link com.karalisoft.scad.SphereParams#getD <em>D</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>D</em>'.
   * @see com.karalisoft.scad.SphereParams#getD()
   * @see #getSphereParams()
   * @generated
   */
  EAttribute getSphereParams_D();

  /**
   * Returns the meta object for class '{@link com.karalisoft.scad.Cylinder <em>Cylinder</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cylinder</em>'.
   * @see com.karalisoft.scad.Cylinder
   * @generated
   */
  EClass getCylinder();

  /**
   * Returns the meta object for the containment reference list '{@link com.karalisoft.scad.Cylinder#getCylinderParams <em>Cylinder Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Cylinder Params</em>'.
   * @see com.karalisoft.scad.Cylinder#getCylinderParams()
   * @see #getCylinder()
   * @generated
   */
  EReference getCylinder_CylinderParams();

  /**
   * Returns the meta object for class '{@link com.karalisoft.scad.CylinderParams <em>Cylinder Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cylinder Params</em>'.
   * @see com.karalisoft.scad.CylinderParams
   * @generated
   */
  EClass getCylinderParams();

  /**
   * Returns the meta object for the attribute '{@link com.karalisoft.scad.CylinderParams#getFn <em>Fn</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Fn</em>'.
   * @see com.karalisoft.scad.CylinderParams#getFn()
   * @see #getCylinderParams()
   * @generated
   */
  EAttribute getCylinderParams_Fn();

  /**
   * Returns the meta object for the attribute '{@link com.karalisoft.scad.CylinderParams#getFa <em>Fa</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Fa</em>'.
   * @see com.karalisoft.scad.CylinderParams#getFa()
   * @see #getCylinderParams()
   * @generated
   */
  EAttribute getCylinderParams_Fa();

  /**
   * Returns the meta object for the attribute '{@link com.karalisoft.scad.CylinderParams#getFs <em>Fs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Fs</em>'.
   * @see com.karalisoft.scad.CylinderParams#getFs()
   * @see #getCylinderParams()
   * @generated
   */
  EAttribute getCylinderParams_Fs();

  /**
   * Returns the meta object for the attribute '{@link com.karalisoft.scad.CylinderParams#getH <em>H</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>H</em>'.
   * @see com.karalisoft.scad.CylinderParams#getH()
   * @see #getCylinderParams()
   * @generated
   */
  EAttribute getCylinderParams_H();

  /**
   * Returns the meta object for the attribute '{@link com.karalisoft.scad.CylinderParams#getR <em>R</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>R</em>'.
   * @see com.karalisoft.scad.CylinderParams#getR()
   * @see #getCylinderParams()
   * @generated
   */
  EAttribute getCylinderParams_R();

  /**
   * Returns the meta object for the attribute '{@link com.karalisoft.scad.CylinderParams#getR1 <em>R1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>R1</em>'.
   * @see com.karalisoft.scad.CylinderParams#getR1()
   * @see #getCylinderParams()
   * @generated
   */
  EAttribute getCylinderParams_R1();

  /**
   * Returns the meta object for the attribute '{@link com.karalisoft.scad.CylinderParams#getR2 <em>R2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>R2</em>'.
   * @see com.karalisoft.scad.CylinderParams#getR2()
   * @see #getCylinderParams()
   * @generated
   */
  EAttribute getCylinderParams_R2();

  /**
   * Returns the meta object for the attribute '{@link com.karalisoft.scad.CylinderParams#getD <em>D</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>D</em>'.
   * @see com.karalisoft.scad.CylinderParams#getD()
   * @see #getCylinderParams()
   * @generated
   */
  EAttribute getCylinderParams_D();

  /**
   * Returns the meta object for the attribute '{@link com.karalisoft.scad.CylinderParams#getD1 <em>D1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>D1</em>'.
   * @see com.karalisoft.scad.CylinderParams#getD1()
   * @see #getCylinderParams()
   * @generated
   */
  EAttribute getCylinderParams_D1();

  /**
   * Returns the meta object for the attribute '{@link com.karalisoft.scad.CylinderParams#getD2 <em>D2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>D2</em>'.
   * @see com.karalisoft.scad.CylinderParams#getD2()
   * @see #getCylinderParams()
   * @generated
   */
  EAttribute getCylinderParams_D2();

  /**
   * Returns the meta object for the attribute '{@link com.karalisoft.scad.CylinderParams#getCenter <em>Center</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Center</em>'.
   * @see com.karalisoft.scad.CylinderParams#getCenter()
   * @see #getCylinderParams()
   * @generated
   */
  EAttribute getCylinderParams_Center();

  /**
   * Returns the meta object for class '{@link com.karalisoft.scad.Cube <em>Cube</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cube</em>'.
   * @see com.karalisoft.scad.Cube
   * @generated
   */
  EClass getCube();

  /**
   * Returns the meta object for the containment reference list '{@link com.karalisoft.scad.Cube#getCubeParams <em>Cube Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Cube Params</em>'.
   * @see com.karalisoft.scad.Cube#getCubeParams()
   * @see #getCube()
   * @generated
   */
  EReference getCube_CubeParams();

  /**
   * Returns the meta object for class '{@link com.karalisoft.scad.CubeParams <em>Cube Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cube Params</em>'.
   * @see com.karalisoft.scad.CubeParams
   * @generated
   */
  EClass getCubeParams();

  /**
   * Returns the meta object for the attribute '{@link com.karalisoft.scad.CubeParams#getSize <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Size</em>'.
   * @see com.karalisoft.scad.CubeParams#getSize()
   * @see #getCubeParams()
   * @generated
   */
  EAttribute getCubeParams_Size();

  /**
   * Returns the meta object for the attribute '{@link com.karalisoft.scad.CubeParams#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see com.karalisoft.scad.CubeParams#getX()
   * @see #getCubeParams()
   * @generated
   */
  EAttribute getCubeParams_X();

  /**
   * Returns the meta object for the attribute '{@link com.karalisoft.scad.CubeParams#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see com.karalisoft.scad.CubeParams#getY()
   * @see #getCubeParams()
   * @generated
   */
  EAttribute getCubeParams_Y();

  /**
   * Returns the meta object for the attribute '{@link com.karalisoft.scad.CubeParams#getZ <em>Z</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Z</em>'.
   * @see com.karalisoft.scad.CubeParams#getZ()
   * @see #getCubeParams()
   * @generated
   */
  EAttribute getCubeParams_Z();

  /**
   * Returns the meta object for the attribute '{@link com.karalisoft.scad.CubeParams#getCenter <em>Center</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Center</em>'.
   * @see com.karalisoft.scad.CubeParams#getCenter()
   * @see #getCubeParams()
   * @generated
   */
  EAttribute getCubeParams_Center();

  /**
   * Returns the meta object for class '{@link com.karalisoft.scad.Union <em>Union</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Union</em>'.
   * @see com.karalisoft.scad.Union
   * @generated
   */
  EClass getUnion();

  /**
   * Returns the meta object for the containment reference list '{@link com.karalisoft.scad.Union#getShapes <em>Shapes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Shapes</em>'.
   * @see com.karalisoft.scad.Union#getShapes()
   * @see #getUnion()
   * @generated
   */
  EReference getUnion_Shapes();

  /**
   * Returns the meta object for class '{@link com.karalisoft.scad.Intersection <em>Intersection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Intersection</em>'.
   * @see com.karalisoft.scad.Intersection
   * @generated
   */
  EClass getIntersection();

  /**
   * Returns the meta object for the containment reference list '{@link com.karalisoft.scad.Intersection#getShapes <em>Shapes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Shapes</em>'.
   * @see com.karalisoft.scad.Intersection#getShapes()
   * @see #getIntersection()
   * @generated
   */
  EReference getIntersection_Shapes();

  /**
   * Returns the meta object for class '{@link com.karalisoft.scad.Difference <em>Difference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Difference</em>'.
   * @see com.karalisoft.scad.Difference
   * @generated
   */
  EClass getDifference();

  /**
   * Returns the meta object for the containment reference list '{@link com.karalisoft.scad.Difference#getShapes <em>Shapes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Shapes</em>'.
   * @see com.karalisoft.scad.Difference#getShapes()
   * @see #getDifference()
   * @generated
   */
  EReference getDifference_Shapes();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ScadFactory getScadFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.karalisoft.scad.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.karalisoft.scad.impl.ModelImpl
     * @see com.karalisoft.scad.impl.ScadPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Blocks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__BLOCKS = eINSTANCE.getModel_Blocks();

    /**
     * The meta object literal for the '{@link com.karalisoft.scad.impl.ModuleOrFunctionImpl <em>Module Or Function</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.karalisoft.scad.impl.ModuleOrFunctionImpl
     * @see com.karalisoft.scad.impl.ScadPackageImpl#getModuleOrFunction()
     * @generated
     */
    EClass MODULE_OR_FUNCTION = eINSTANCE.getModuleOrFunction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODULE_OR_FUNCTION__NAME = eINSTANCE.getModuleOrFunction_Name();

    /**
     * The meta object literal for the '{@link com.karalisoft.scad.impl.UseOrIncludeImpl <em>Use Or Include</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.karalisoft.scad.impl.UseOrIncludeImpl
     * @see com.karalisoft.scad.impl.ScadPackageImpl#getUseOrInclude()
     * @generated
     */
    EClass USE_OR_INCLUDE = eINSTANCE.getUseOrInclude();

    /**
     * The meta object literal for the '{@link com.karalisoft.scad.impl.ModuleImpl <em>Module</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.karalisoft.scad.impl.ModuleImpl
     * @see com.karalisoft.scad.impl.ScadPackageImpl#getModule()
     * @generated
     */
    EClass MODULE = eINSTANCE.getModule();

    /**
     * The meta object literal for the '<em><b>Blocks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODULE__BLOCKS = eINSTANCE.getModule_Blocks();

    /**
     * The meta object literal for the '{@link com.karalisoft.scad.impl.FunctionImpl <em>Function</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.karalisoft.scad.impl.FunctionImpl
     * @see com.karalisoft.scad.impl.ScadPackageImpl#getFunction()
     * @generated
     */
    EClass FUNCTION = eINSTANCE.getFunction();

    /**
     * The meta object literal for the '{@link com.karalisoft.scad.impl.ModuleOrFunctionCallImpl <em>Module Or Function Call</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.karalisoft.scad.impl.ModuleOrFunctionCallImpl
     * @see com.karalisoft.scad.impl.ScadPackageImpl#getModuleOrFunctionCall()
     * @generated
     */
    EClass MODULE_OR_FUNCTION_CALL = eINSTANCE.getModuleOrFunctionCall();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODULE_OR_FUNCTION_CALL__NAME = eINSTANCE.getModuleOrFunctionCall_Name();

    /**
     * The meta object literal for the '{@link com.karalisoft.scad.impl.TransformationImpl <em>Transformation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.karalisoft.scad.impl.TransformationImpl
     * @see com.karalisoft.scad.impl.ScadPackageImpl#getTransformation()
     * @generated
     */
    EClass TRANSFORMATION = eINSTANCE.getTransformation();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSFORMATION__X = eINSTANCE.getTransformation_X();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSFORMATION__Y = eINSTANCE.getTransformation_Y();

    /**
     * The meta object literal for the '<em><b>Z</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSFORMATION__Z = eINSTANCE.getTransformation_Z();

    /**
     * The meta object literal for the '{@link com.karalisoft.scad.impl.TranslateImpl <em>Translate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.karalisoft.scad.impl.TranslateImpl
     * @see com.karalisoft.scad.impl.ScadPackageImpl#getTranslate()
     * @generated
     */
    EClass TRANSLATE = eINSTANCE.getTranslate();

    /**
     * The meta object literal for the '{@link com.karalisoft.scad.impl.RotateImpl <em>Rotate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.karalisoft.scad.impl.RotateImpl
     * @see com.karalisoft.scad.impl.ScadPackageImpl#getRotate()
     * @generated
     */
    EClass ROTATE = eINSTANCE.getRotate();

    /**
     * The meta object literal for the '{@link com.karalisoft.scad.impl.ScaleImpl <em>Scale</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.karalisoft.scad.impl.ScaleImpl
     * @see com.karalisoft.scad.impl.ScadPackageImpl#getScale()
     * @generated
     */
    EClass SCALE = eINSTANCE.getScale();

    /**
     * The meta object literal for the '<em><b>Scale</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCALE__SCALE = eINSTANCE.getScale_Scale();

    /**
     * The meta object literal for the '{@link com.karalisoft.scad.impl.ShapeImpl <em>Shape</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.karalisoft.scad.impl.ShapeImpl
     * @see com.karalisoft.scad.impl.ScadPackageImpl#getShape()
     * @generated
     */
    EClass SHAPE = eINSTANCE.getShape();

    /**
     * The meta object literal for the '<em><b>Impl</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SHAPE__IMPL = eINSTANCE.getShape_Impl();

    /**
     * The meta object literal for the '{@link com.karalisoft.scad.impl.TransformedShapeImpl <em>Transformed Shape</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.karalisoft.scad.impl.TransformedShapeImpl
     * @see com.karalisoft.scad.impl.ScadPackageImpl#getTransformedShape()
     * @generated
     */
    EClass TRANSFORMED_SHAPE = eINSTANCE.getTransformedShape();

    /**
     * The meta object literal for the '<em><b>Translations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSFORMED_SHAPE__TRANSLATIONS = eINSTANCE.getTransformedShape_Translations();

    /**
     * The meta object literal for the '<em><b>Impl</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSFORMED_SHAPE__IMPL = eINSTANCE.getTransformedShape_Impl();

    /**
     * The meta object literal for the '{@link com.karalisoft.scad.impl.TransformedModuleOrFunctionCallImpl <em>Transformed Module Or Function Call</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.karalisoft.scad.impl.TransformedModuleOrFunctionCallImpl
     * @see com.karalisoft.scad.impl.ScadPackageImpl#getTransformedModuleOrFunctionCall()
     * @generated
     */
    EClass TRANSFORMED_MODULE_OR_FUNCTION_CALL = eINSTANCE.getTransformedModuleOrFunctionCall();

    /**
     * The meta object literal for the '<em><b>Translations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSFORMED_MODULE_OR_FUNCTION_CALL__TRANSLATIONS = eINSTANCE.getTransformedModuleOrFunctionCall_Translations();

    /**
     * The meta object literal for the '<em><b>Impl</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSFORMED_MODULE_OR_FUNCTION_CALL__IMPL = eINSTANCE.getTransformedModuleOrFunctionCall_Impl();

    /**
     * The meta object literal for the '{@link com.karalisoft.scad.impl.SphereImpl <em>Sphere</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.karalisoft.scad.impl.SphereImpl
     * @see com.karalisoft.scad.impl.ScadPackageImpl#getSphere()
     * @generated
     */
    EClass SPHERE = eINSTANCE.getSphere();

    /**
     * The meta object literal for the '<em><b>Sphere Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SPHERE__SPHERE_PARAMS = eINSTANCE.getSphere_SphereParams();

    /**
     * The meta object literal for the '{@link com.karalisoft.scad.impl.SphereParamsImpl <em>Sphere Params</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.karalisoft.scad.impl.SphereParamsImpl
     * @see com.karalisoft.scad.impl.ScadPackageImpl#getSphereParams()
     * @generated
     */
    EClass SPHERE_PARAMS = eINSTANCE.getSphereParams();

    /**
     * The meta object literal for the '<em><b>Fn</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SPHERE_PARAMS__FN = eINSTANCE.getSphereParams_Fn();

    /**
     * The meta object literal for the '<em><b>Fa</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SPHERE_PARAMS__FA = eINSTANCE.getSphereParams_Fa();

    /**
     * The meta object literal for the '<em><b>Fs</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SPHERE_PARAMS__FS = eINSTANCE.getSphereParams_Fs();

    /**
     * The meta object literal for the '<em><b>R</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SPHERE_PARAMS__R = eINSTANCE.getSphereParams_R();

    /**
     * The meta object literal for the '<em><b>D</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SPHERE_PARAMS__D = eINSTANCE.getSphereParams_D();

    /**
     * The meta object literal for the '{@link com.karalisoft.scad.impl.CylinderImpl <em>Cylinder</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.karalisoft.scad.impl.CylinderImpl
     * @see com.karalisoft.scad.impl.ScadPackageImpl#getCylinder()
     * @generated
     */
    EClass CYLINDER = eINSTANCE.getCylinder();

    /**
     * The meta object literal for the '<em><b>Cylinder Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CYLINDER__CYLINDER_PARAMS = eINSTANCE.getCylinder_CylinderParams();

    /**
     * The meta object literal for the '{@link com.karalisoft.scad.impl.CylinderParamsImpl <em>Cylinder Params</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.karalisoft.scad.impl.CylinderParamsImpl
     * @see com.karalisoft.scad.impl.ScadPackageImpl#getCylinderParams()
     * @generated
     */
    EClass CYLINDER_PARAMS = eINSTANCE.getCylinderParams();

    /**
     * The meta object literal for the '<em><b>Fn</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CYLINDER_PARAMS__FN = eINSTANCE.getCylinderParams_Fn();

    /**
     * The meta object literal for the '<em><b>Fa</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CYLINDER_PARAMS__FA = eINSTANCE.getCylinderParams_Fa();

    /**
     * The meta object literal for the '<em><b>Fs</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CYLINDER_PARAMS__FS = eINSTANCE.getCylinderParams_Fs();

    /**
     * The meta object literal for the '<em><b>H</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CYLINDER_PARAMS__H = eINSTANCE.getCylinderParams_H();

    /**
     * The meta object literal for the '<em><b>R</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CYLINDER_PARAMS__R = eINSTANCE.getCylinderParams_R();

    /**
     * The meta object literal for the '<em><b>R1</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CYLINDER_PARAMS__R1 = eINSTANCE.getCylinderParams_R1();

    /**
     * The meta object literal for the '<em><b>R2</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CYLINDER_PARAMS__R2 = eINSTANCE.getCylinderParams_R2();

    /**
     * The meta object literal for the '<em><b>D</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CYLINDER_PARAMS__D = eINSTANCE.getCylinderParams_D();

    /**
     * The meta object literal for the '<em><b>D1</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CYLINDER_PARAMS__D1 = eINSTANCE.getCylinderParams_D1();

    /**
     * The meta object literal for the '<em><b>D2</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CYLINDER_PARAMS__D2 = eINSTANCE.getCylinderParams_D2();

    /**
     * The meta object literal for the '<em><b>Center</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CYLINDER_PARAMS__CENTER = eINSTANCE.getCylinderParams_Center();

    /**
     * The meta object literal for the '{@link com.karalisoft.scad.impl.CubeImpl <em>Cube</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.karalisoft.scad.impl.CubeImpl
     * @see com.karalisoft.scad.impl.ScadPackageImpl#getCube()
     * @generated
     */
    EClass CUBE = eINSTANCE.getCube();

    /**
     * The meta object literal for the '<em><b>Cube Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CUBE__CUBE_PARAMS = eINSTANCE.getCube_CubeParams();

    /**
     * The meta object literal for the '{@link com.karalisoft.scad.impl.CubeParamsImpl <em>Cube Params</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.karalisoft.scad.impl.CubeParamsImpl
     * @see com.karalisoft.scad.impl.ScadPackageImpl#getCubeParams()
     * @generated
     */
    EClass CUBE_PARAMS = eINSTANCE.getCubeParams();

    /**
     * The meta object literal for the '<em><b>Size</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CUBE_PARAMS__SIZE = eINSTANCE.getCubeParams_Size();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CUBE_PARAMS__X = eINSTANCE.getCubeParams_X();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CUBE_PARAMS__Y = eINSTANCE.getCubeParams_Y();

    /**
     * The meta object literal for the '<em><b>Z</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CUBE_PARAMS__Z = eINSTANCE.getCubeParams_Z();

    /**
     * The meta object literal for the '<em><b>Center</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CUBE_PARAMS__CENTER = eINSTANCE.getCubeParams_Center();

    /**
     * The meta object literal for the '{@link com.karalisoft.scad.impl.UnionImpl <em>Union</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.karalisoft.scad.impl.UnionImpl
     * @see com.karalisoft.scad.impl.ScadPackageImpl#getUnion()
     * @generated
     */
    EClass UNION = eINSTANCE.getUnion();

    /**
     * The meta object literal for the '<em><b>Shapes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UNION__SHAPES = eINSTANCE.getUnion_Shapes();

    /**
     * The meta object literal for the '{@link com.karalisoft.scad.impl.IntersectionImpl <em>Intersection</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.karalisoft.scad.impl.IntersectionImpl
     * @see com.karalisoft.scad.impl.ScadPackageImpl#getIntersection()
     * @generated
     */
    EClass INTERSECTION = eINSTANCE.getIntersection();

    /**
     * The meta object literal for the '<em><b>Shapes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTERSECTION__SHAPES = eINSTANCE.getIntersection_Shapes();

    /**
     * The meta object literal for the '{@link com.karalisoft.scad.impl.DifferenceImpl <em>Difference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.karalisoft.scad.impl.DifferenceImpl
     * @see com.karalisoft.scad.impl.ScadPackageImpl#getDifference()
     * @generated
     */
    EClass DIFFERENCE = eINSTANCE.getDifference();

    /**
     * The meta object literal for the '<em><b>Shapes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIFFERENCE__SHAPES = eINSTANCE.getDifference_Shapes();

  }

} //ScadPackage
