/**
 * generated by Xtext 2.24.0
 */
package com.karalisoft.scad;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Scale</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.karalisoft.scad.Scale#getScale <em>Scale</em>}</li>
 * </ul>
 *
 * @see com.karalisoft.scad.ScadPackage#getScale()
 * @model
 * @generated
 */
public interface Scale extends Transformation
{
  /**
   * Returns the value of the '<em><b>Scale</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scale</em>' attribute.
   * @see #setScale(Double)
   * @see com.karalisoft.scad.ScadPackage#getScale_Scale()
   * @model
   * @generated
   */
  Double getScale();

  /**
   * Sets the value of the '{@link com.karalisoft.scad.Scale#getScale <em>Scale</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Scale</em>' attribute.
   * @see #getScale()
   * @generated
   */
  void setScale(Double value);

} // Scale
