/**
 * generated by Xtext 2.24.0
 */
package com.karalisoft.scad;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sphere Params</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.karalisoft.scad.SphereParams#getFn <em>Fn</em>}</li>
 *   <li>{@link com.karalisoft.scad.SphereParams#getFa <em>Fa</em>}</li>
 *   <li>{@link com.karalisoft.scad.SphereParams#getFs <em>Fs</em>}</li>
 *   <li>{@link com.karalisoft.scad.SphereParams#getR <em>R</em>}</li>
 *   <li>{@link com.karalisoft.scad.SphereParams#getD <em>D</em>}</li>
 * </ul>
 *
 * @see com.karalisoft.scad.ScadPackage#getSphereParams()
 * @model
 * @generated
 */
public interface SphereParams extends EObject
{
  /**
   * Returns the value of the '<em><b>Fn</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fn</em>' attribute.
   * @see #setFn(Double)
   * @see com.karalisoft.scad.ScadPackage#getSphereParams_Fn()
   * @model
   * @generated
   */
  Double getFn();

  /**
   * Sets the value of the '{@link com.karalisoft.scad.SphereParams#getFn <em>Fn</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fn</em>' attribute.
   * @see #getFn()
   * @generated
   */
  void setFn(Double value);

  /**
   * Returns the value of the '<em><b>Fa</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fa</em>' attribute.
   * @see #setFa(Double)
   * @see com.karalisoft.scad.ScadPackage#getSphereParams_Fa()
   * @model
   * @generated
   */
  Double getFa();

  /**
   * Sets the value of the '{@link com.karalisoft.scad.SphereParams#getFa <em>Fa</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fa</em>' attribute.
   * @see #getFa()
   * @generated
   */
  void setFa(Double value);

  /**
   * Returns the value of the '<em><b>Fs</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fs</em>' attribute.
   * @see #setFs(Double)
   * @see com.karalisoft.scad.ScadPackage#getSphereParams_Fs()
   * @model
   * @generated
   */
  Double getFs();

  /**
   * Sets the value of the '{@link com.karalisoft.scad.SphereParams#getFs <em>Fs</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fs</em>' attribute.
   * @see #getFs()
   * @generated
   */
  void setFs(Double value);

  /**
   * Returns the value of the '<em><b>R</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>R</em>' attribute.
   * @see #setR(Double)
   * @see com.karalisoft.scad.ScadPackage#getSphereParams_R()
   * @model
   * @generated
   */
  Double getR();

  /**
   * Sets the value of the '{@link com.karalisoft.scad.SphereParams#getR <em>R</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>R</em>' attribute.
   * @see #getR()
   * @generated
   */
  void setR(Double value);

  /**
   * Returns the value of the '<em><b>D</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>D</em>' attribute.
   * @see #setD(Double)
   * @see com.karalisoft.scad.ScadPackage#getSphereParams_D()
   * @model
   * @generated
   */
  Double getD();

  /**
   * Sets the value of the '{@link com.karalisoft.scad.SphereParams#getD <em>D</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>D</em>' attribute.
   * @see #getD()
   * @generated
   */
  void setD(Double value);

} // SphereParams
