/**
 * generated by Xtext 2.24.0
 */
package com.karalisoft.scad;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Translate</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.karalisoft.scad.ScadPackage#getTranslate()
 * @model
 * @generated
 */
public interface Translate extends Transformation
{
} // Translate
