/**
 * generated by Xtext 2.24.0
 */
package com.karalisoft.scad;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transformed Module Or Function Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.karalisoft.scad.TransformedModuleOrFunctionCall#getTranslations <em>Translations</em>}</li>
 *   <li>{@link com.karalisoft.scad.TransformedModuleOrFunctionCall#getImpl <em>Impl</em>}</li>
 * </ul>
 *
 * @see com.karalisoft.scad.ScadPackage#getTransformedModuleOrFunctionCall()
 * @model
 * @generated
 */
public interface TransformedModuleOrFunctionCall extends EObject
{
  /**
   * Returns the value of the '<em><b>Translations</b></em>' containment reference list.
   * The list contents are of type {@link com.karalisoft.scad.Transformation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Translations</em>' containment reference list.
   * @see com.karalisoft.scad.ScadPackage#getTransformedModuleOrFunctionCall_Translations()
   * @model containment="true"
   * @generated
   */
  EList<Transformation> getTranslations();

  /**
   * Returns the value of the '<em><b>Impl</b></em>' containment reference list.
   * The list contents are of type {@link com.karalisoft.scad.ModuleOrFunctionCall}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Impl</em>' containment reference list.
   * @see com.karalisoft.scad.ScadPackage#getTransformedModuleOrFunctionCall_Impl()
   * @model containment="true"
   * @generated
   */
  EList<ModuleOrFunctionCall> getImpl();

} // TransformedModuleOrFunctionCall
