/**
 * generated by Xtext 2.24.0
 */
package com.karalisoft.scad;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transformation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.karalisoft.scad.Transformation#getX <em>X</em>}</li>
 *   <li>{@link com.karalisoft.scad.Transformation#getY <em>Y</em>}</li>
 *   <li>{@link com.karalisoft.scad.Transformation#getZ <em>Z</em>}</li>
 * </ul>
 *
 * @see com.karalisoft.scad.ScadPackage#getTransformation()
 * @model
 * @generated
 */
public interface Transformation extends EObject
{
  /**
   * Returns the value of the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>X</em>' attribute.
   * @see #setX(Double)
   * @see com.karalisoft.scad.ScadPackage#getTransformation_X()
   * @model
   * @generated
   */
  Double getX();

  /**
   * Sets the value of the '{@link com.karalisoft.scad.Transformation#getX <em>X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X</em>' attribute.
   * @see #getX()
   * @generated
   */
  void setX(Double value);

  /**
   * Returns the value of the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Y</em>' attribute.
   * @see #setY(Double)
   * @see com.karalisoft.scad.ScadPackage#getTransformation_Y()
   * @model
   * @generated
   */
  Double getY();

  /**
   * Sets the value of the '{@link com.karalisoft.scad.Transformation#getY <em>Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Y</em>' attribute.
   * @see #getY()
   * @generated
   */
  void setY(Double value);

  /**
   * Returns the value of the '<em><b>Z</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Z</em>' attribute.
   * @see #setZ(Double)
   * @see com.karalisoft.scad.ScadPackage#getTransformation_Z()
   * @model
   * @generated
   */
  Double getZ();

  /**
   * Sets the value of the '{@link com.karalisoft.scad.Transformation#getZ <em>Z</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Z</em>' attribute.
   * @see #getZ()
   * @generated
   */
  void setZ(Double value);

} // Transformation
