/**
 * generated by Xtext 2.24.0
 */
package com.karalisoft.scad;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Use Or Include</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.karalisoft.scad.ScadPackage#getUseOrInclude()
 * @model
 * @generated
 */
public interface UseOrInclude extends EObject
{
} // UseOrInclude
