/*
 * generated by Xtext 2.24.0
 */
package com.karalisoft.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractScadScopeProvider extends DelegatingScopeProvider {
}
