/*
 * generated by Xtext 2.19.0
 */
package com.karalisoft

import com.karalisoft.generator.ScadOutputConfigurationProvider
import org.eclipse.xtext.generator.IOutputConfigurationProvider

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ScadRuntimeModule extends AbstractScadRuntimeModule {
	def Class<? extends IOutputConfigurationProvider> bindIOutputConfigurationProvider() {
		return ScadOutputConfigurationProvider
	}
}
