/*
 * generated by Xtext 2.19.0
 */
package com.karalisoft


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ScadStandaloneSetup extends ScadStandaloneSetupGenerated {

	def static void doSetup() {
		new ScadStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
